# Generated by Django 3.1.1 on 2020-09-28 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exotom', '0002_transitdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='transitdetails',
            name='facility',
            field=models.TextField(default='IAG50', verbose_name='Name of facility.'),
            preserve_default=False,
        ),
        migrations.AlterIndexTogether(
            name='transitdetails',
            index_together={('transit', 'facility', 'site')},
        ),
    ]
