# Generated by Django 3.1.5 on 2021-01-14 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exotom', '0003_auto_20200928_1430'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TransitDetails',
            new_name='TransitObservationDetails',
        ),
    ]
