# Generated by Django 3.1.5 on 2021-01-21 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exotom", "0004_auto_20210114_1341"),
    ]

    operations = [
        migrations.AddField(
            model_name="transitobservationdetails",
            name="visible",
            field=models.BooleanField(
                null=True, verbose_name="Whether transit is visible"
            ),
        ),
        migrations.AlterField(
            model_name="transitobservationdetails",
            name="observable",
            field=models.BooleanField(
                null=True, verbose_name="Whether transit can be observed at this site"
            ),
        ),
    ]
