# Generated by Django 3.1.5 on 2021-01-27 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exotom", "0005_auto_20210121_1240"),
    ]

    operations = [
        migrations.AddField(
            model_name="transitobservationdetails",
            name="egress_observable",
            field=models.BooleanField(
                null=True,
                verbose_name="Whether transit egress can be observed at this site",
            ),
        ),
        migrations.AddField(
            model_name="transitobservationdetails",
            name="egress_visible",
            field=models.BooleanField(
                null=True, verbose_name="Whether transit egress is visible"
            ),
        ),
        migrations.AddField(
            model_name="transitobservationdetails",
            name="ingress_observable",
            field=models.BooleanField(
                null=True,
                verbose_name="Whether transit ingress can be observed at this site",
            ),
        ),
        migrations.AddField(
            model_name="transitobservationdetails",
            name="ingress_visible",
            field=models.BooleanField(
                null=True, verbose_name="Whether transit ingress is visible"
            ),
        ),
    ]
